// Copyright (c) 2019, 2021 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: podman
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-releasedate: 2019-07-23
:page-description: Learn how to containerize and run your microservices with Open Liberty using Podman
:page-permalink: /guides/{projectid}
:page-related-guides: ['containerize', 'docker', 'kubernetes-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:source-highlighter: prettify
:page-seo-title: Containerizing and running Java microservices in Podman containers
:page-seo-description: A getting started tutorial with examples of how to containerize or dockerize your Java microservices by building a container image and running the image as a Podman container.
:guide-author: Open Liberty
= Containerizing microservices

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the  https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to containerize and run your microservices with Open Liberty using Podman.

// =================================================================================================
//  What you'll learn
// =================================================================================================

== What you'll learn


You can easily deploy your microservices in different environments in a lightweight and portable manner by using containers.
From development to production and across your DevOps environments, you can deploy your microservices consistently and
efficiently with containers. You can run a container from a container image. Each container image is a package of what you
need to run your microservice or application, from the code to its dependencies and configuration.

You'll learn how to build container images and run containers using Podman for your microservices.
You'll construct `Dockerfile` files, create Podman images by using the `podman build` command, and run the image as Podman containers 
by using `podman run` command.

The two microservices that you'll be working with are called `system` and `inventory`. The `system` microservice returns the JVM system properties 
of the running container. The `inventory` microservice adds the properties from the `system` microservice to the inventory. This guide demonstrates how both microservices can run and communicate
with each other in different Podman containers. 

== Additional prerequisites

Before you begin, Podman needs to be installed. For installation instructions, refer to the https://podman.io/getting-started/installation[official Podman documentation^]. You will build and run the microservices in Podman containers.


///////////////////////////
// Getting started
///////////////////////////

[role='command']
include::{common-includes}/gitclone.adoc[]


== Packaging your microservices

// static guide instructions:
ifndef::cloud-hosted[]
Navigate to the `start` directory to begin.
endif::[]

// cloud-hosted guide instructions:
ifdef::cloud-hosted[]
To begin, run the following command to navigate to the **start** directory:
```
cd start
```
{: codeblock}
endif::[]

You can find the starting Java project in the `start` directory. It is a multi-module Maven project that is made up of the `system` and `inventory` microservices. Each microservice lives in its own corresponding directory, `system` and `inventory`.

To try out the microservices by using Maven, run the following Maven goal to build the `system` microservice and run it inside Open Liberty:
[role='command']
```
mvn -pl system liberty:run
```

// static guide instructions:
ifndef::cloud-hosted[]
Open another command-line session and run the following Maven goal to build the `inventory` microservice and run it inside Open Liberty:
[role='command']
```
mvn -pl inventory liberty:run
```

After you see the following message in both command-line sessions, both of your services are ready:

[source, role="no_copy"]
----
The defaultServer server is ready to run a smarter planet.
----

To access the `inventory` service, which displays the current contents of the inventory, see http://localhost:9081/inventory/systems[http://localhost:9081/inventory/systems^].

The `system` service shows the system properties of the running JVM and can be found at  http://localhost:9080/system/properties[^].

The system properties of your localhost can be added to the `inventory` service at http://localhost:9081/inventory/systems/localhost[http://localhost:9081/inventory/systems/localhost^].
endif::[]

// cloud-hosted guide instructions:
ifdef::cloud-hosted[]
Select **Terminal** > **New Terminal** from the menu of the IDE to open another command-line session and 
run the following Maven goal to build the **inventory** microservice and run it inside Open Liberty:
```
cd /home/project/guide-podman/start
mvn -pl inventory liberty:run
```
{: codeblock}

Select **Terminal** > **New Terminal** from the menu of the IDE to open a new command-line session.
To access the **inventory** service, which displays the current contents of the inventory, run the following curl command: 
```
curl -s http://localhost:9081/inventory/systems | jq
```
{: codeblock}

After you see the following message in both command-line sessions, both of your services are ready:

```
The defaultServer server is ready to run a smarter planet.
```

The **system** service shows the system properties of the running JVM and can be found by running the following curl command:
```
curl -s http://localhost:9080/system/properties | jq
```
{: codeblock}

The system properties of your localhost can be added to the **inventory** service at **http://localhost:9081/inventory/systems/localhost**. Run the following curl command:
```
curl -s http://localhost:9081/inventory/systems/localhost | jq
```
{: codeblock}
endif::[]

// static guide instructions:
ifndef::cloud-hosted[]
After you are finished checking out the microservices, stop the Open Liberty servers by pressing `CTRL+C`
in the command-line sessions where you ran the servers. Alternatively, you can run the `liberty:stop` goal in another command-line session:
[role='command']
```
mvn -pl system liberty:stop
mvn -pl inventory liberty:stop
```
endif::[]

// cloud-hosted guide instructions:
ifdef::cloud-hosted[]
After you are finished checking out the microservices, stop the Open Liberty servers by pressing **CTRL+C**
in the command-line sessions where you ran the servers. Alternatively, you can run the **liberty:stop** goal in another command-line session from the 
**start** directory:
```
cd /home/project/guide-containerize/start
mvn -pl system liberty:stop
mvn -pl inventory liberty:stop
```
{: codeblock}
endif::[]

Run the Maven `package` goal to build the application `.war` files from the `start` directory so that the `.war` files reside in the `system/target` and `inventory/target` directories.
[role='command']
```
mvn package
```

To learn more about RESTful web services and how to build them, see
https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service^] for details about how to build the `system` service.
The `inventory` service is built in a similar way.


== Building your Podman images

A Podman image is a binary file. It is made up of multiple layers and is used to run code in a Podman container. Images are built from
instructions in Dockerfiles to create a containerized version of the application.

A `Dockerfile` is a collection of instructions for building a Docker image that can then be run as a container. They can be interpreted by Podman as well.
As each instruction is run in a `Dockerfile`, a new Podman layer is created. These layers, which are known as intermediate images, are created when a change is made to your Podman image.

Every `Dockerfile` begins with a parent or base image over which various commands are run. For example, you can start your image from scratch and run commands that download and install a Java runtime, or you can start from an image that already contains a Java installation.

Learn more about Podman on the https://podman.io/getting-started/[official Podman page^].

=== Creating your Dockerfiles
You will be creating two Podman images to run the `inventory` service and `system` service. The first step is to create Dockerfiles for both services.

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `Dockerfile` for the inventory service.#
`inventory/Dockerfile`
----

inventory/Dockerfile
[source, Text, linenums, indent=0, role="code_column"]
----
include::finish/inventory/Dockerfile[]
----

The [hotspot=from file=0]`FROM` instruction initializes a new build stage, which indicates the parent image of the built image. If you don't need a parent image, then you can use `FROM scratch`, which makes your image a base image. 

In this case, you're using the recommended production image,
`icr.io/appcafe/open-liberty:full-java11-openj9-ubi`, as your parent image. If you
don't want any additional runtime features for your `kernel` image, define the
`FROM` instruction as `FROM open-liberty:kernel-slim`. To use the default image that
comes with the Open Liberty runtime, define the `FROM` instruction as `FROM open-liberty`. 
You can find all the https://hub.docker.com/_/open-liberty[official images^] and
https://hub.docker.com/r/openliberty/open-liberty/[ubi images^] on the open-liberty Docker Hub.

It is also recommended to label your Podman images with the [hotspot=label file=0]`LABEL` command, as the label information can help you manage your images. For more information, see https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#label[Best practices for writing Dockerfiles^].

The [hotspot=copy-config hotspot=copy-war file=0]`COPY` instructions are structured as `COPY` [hotspot=config-userID hotspot=war-userID file=0]`[--chown=<user>:<group>]` [hotspot=inventory-config hotspot=inventory-war file=0]`<source>` [hotspot=config hotspot=config-apps file=0]`<destination>`. 
They copy local files into the specified destination within your Podman image.
In this case, the `inventory` server configuration files that are located at `src/main/liberty/config` are copied to the [hotspot=config file=0]`/config/` destination directory.
The `inventory` application WAR file [hotspot=inventory-war file=0]`inventory.war`, which was created from running `mvn package`, is copied to the [hotspot=config-apps file=0]`/config/apps` destination directory.

The [hotspot=copy-config hotspot=copy-war file=0]`COPY` instructions use the [hotspot=config-userID hotspot=war-userID file=0]`1001` user ID  and [hotspot=config-userID hotspot=war-userID file=0]`0` group because the `icr.io/appcafe/open-liberty:full-java11-openj9-ubi` image runs by default with the `USER 1001` (non-root) user for security purposes. Otherwise, the files and directories that are copied over are owned by the root user.

Place the [hotspot=configure-sh file=0]`RUN configure.sh` command at the end to get a pre-warmed Podman image. It improves the startup time of running your Podman container.

The `Dockerfile` for the `system` service follows the same instructions as the `inventory` service, except that some [hotspot=name hotspot=summary file=1]`labels` are updated, and the [hotspot=copy-war file=1]`system.war` archive is copied into `/config/apps`.

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `Dockerfile` for the system service.#
`system/Dockerfile`
----

system/Dockerfile
[source, Text, linenums, indent=0, role="code_column"]
----
include::finish/system/Dockerfile[]
----


=== Building your Podman image

Now that your microservices are packaged and you have written your Dockerfiles, you will build your Podman images by using the `podman build` command.

Run the following command to download or update to the latest Open Liberty Docker image:

[role='command']
```
podman pull icr.io/appcafe/open-liberty:full-java11-openj9-ubi
```

Run the following commands to build container images for your application:

[role='command']
```
podman build -t system:1.0-SNAPSHOT system/.
podman build -t inventory:1.0-SNAPSHOT inventory/.
```

The `-t` flag in the `podman build` command allows the Podman image to be labeled (tagged) in the `name[:tag]` format. 
The tag for an image describes the specific image version. If the optional `[:tag]` tag is not specified, the `latest` tag is created by default.

To verify that the images are built, run the `podman images` command to list all local Podman images:

[role='command']
```
podman images
```

Or, run the `podman images` command with `--filter` option to list your images:
[role='command']
```
podman images -f "label=org.opencontainers.image.authors=Your Name"
```

Your two images, `inventory` and `system`, should appear in the list of all Podman images:

[role="no_copy"]
----
REPOSITORY    TAG             IMAGE ID        CREATED          SIZE
inventory     1.0-SNAPSHOT    08fef024e986    4 minutes ago    471MB
system        1.0-SNAPSHOT    1dff6d0b4f31    5 minutes ago    470MB
----


== Running your microservices in Podman containers
Now that you have your two images built, you will run your microservices in Podman containers:

[role='command']
```
podman run -d --name system -p 9080:9080 system:1.0-SNAPSHOT
podman run -d --name inventory -p 9081:9081 inventory:1.0-SNAPSHOT
```

The flags are described in the table below: 

[cols="15, 100", options="header"]
|===
| *Flag* | *Description*
| -d     | Runs the container in the background.
| --name | Specifies a name for the container.
| -p     | Maps the host ports to the container ports. For example: `-p <HOST_PORT>:<CONTAINER_PORT>`
|===

Next, run the `podman ps` command to verify that your containers are started:

[role='command']
```
podman ps
```

Make sure that your containers are running and show `Up` as their status:

[role="no_copy"]
----
CONTAINER ID    IMAGE                   COMMAND                  CREATED          STATUS          PORTS                                        NAMES
2b584282e0f5    inventory:1.0-SNAPSHOT  "/opt/ol/helpers/run…"   2 seconds ago    Up 1 second     9080/tcp, 9443/tcp, 0.0.0.0:9081->9081/tcp   inventory
99a98313705f    system:1.0-SNAPSHOT     "/opt/ol/helpers/run…"   3 seconds ago    Up 2 seconds    0.0.0.0:9080->9080/tcp, 9443/tcp             system
----

If a problem occurs and your containers exit prematurely, the containers don't appear in the container
list that the `podman ps` command displays. Instead, your containers appear with an `Exited`
status when they run the `podman ps -a` command. Run the `podman logs system` and `podman logs inventory` commands to view the
container logs for any potential problems. Run the `podman stats system` and `podman stats inventory` commands to display a live stream of usage statistics for your containers. You can also double-check that your Dockerfiles are correct. When you
find the cause of the issues, remove the faulty containers with the `podman rm system` and `podman rm inventory` commands. Rebuild
your images, and start the containers again.

// static guide instructions:
ifndef::cloud-hosted[]
To access the application, go to the http://localhost:9081/inventory/systems[http://localhost:9081/inventory/systems^] URL. 
An empty list is expected because no system properties are stored in the inventory yet. 
endif::[]

// cloud-hosted guide instructions:
ifdef::cloud-hosted[]
To access the application, run the following curl command. 
An empty list is expected because no system properties are stored in the inventory yet:
```
curl -s http://localhost:9081/inventory/systems | jq
```
{: codeblock}
endif::[]

Next, retrieve the `system` container's IP address by using the `system` container's name that is defined when it ran the Podman containers. 
Run the following command to retrieve the `system` IP address:

[role='command']
```
podman inspect -f "{{.NetworkSettings.IPAddress }}" system
```

You find the `system` container's IP address:

[role="no_copy"]
----
172.17.0.2
----

In this case, the IP address for the `system` service is `172.17.0.2`. Take note of this IP address to add the system properties to the `inventory` service. 

// static guide instructions:
ifndef::cloud-hosted[]
Go to the `\http://localhost:9081/inventory/systems/pass:c[[system-ip-address]]` URL by replacing `[system-ip-address]` with the IP address that you obtained earlier.
You see a result in JSON format with the system properties of your local JVM. When you go to this URL, these system
properties are automatically stored in the inventory. Go back to the http://localhost:9081/inventory/systems[http://localhost:9081/inventory/systems^] URL and
you see a new entry for `[system-ip-address]`. 
endif::[]

// cloud-hosted guide instructions:
ifdef::cloud-hosted[]
Run the following commands to go to the **http://localhost:9081/inventory/systems/[system-ip-address]** by replacing **[system-ip-address]** URL with the IP address that you obtained earlier:
```
SYSTEM_IP=`podman inspect -f "{{.NetworkSettings.IPAddress }}" system`
curl -s http://localhost:9081/inventory/systems/{$SYSTEM_IP} | jq
```
{: codeblock}

You see a result in JSON format with the system properties of your local JVM. When you visit this URL, these system
properties are automatically stored in the inventory. Run the following curl command and 
you see a new entry for **[system-ip-address]**:
```
curl -s http://localhost:9081/inventory/systems | jq
```
{: codeblock}
endif::[]

== Externalizing server configuration

// File 0
inventory/server.xml
[source, xml, linenums, indent=0, role="code_column"]
----
include::finish/inventory/src/main/liberty/config/server.xml[]
----

As mentioned at the beginning of this guide, one of the advantages of using
containers is that they are portable and can be moved and deployed efficiently
across all of your DevOps environments. Configuration often changes across
different environments, and by externalizing your server configuration, you
can simplify the development process.

Imagine a scenario where you are developing an Open Liberty application on
port `9081` but to deploy it to production, it must be available
on port `9091`. To manage this scenario, you can keep two different versions of the
`server.xml` file; one for production and one for development. However, trying to
maintain two different versions of a file might lead to mistakes. A better
solution would be to externalize the configuration of the port number and use the
value of an environment variable that is stored in each environment. 

In this example, you will use an environment variable to externally configure the
HTTP port number of the `inventory` service. 

In the [hotspot file=0]`inventory/server.xml` file, 
the [hotspot=httpPort file=0]`default.http.port` variable is declared and is used in the
[hotspot=httpEndpoint file=0]`httpEndpoint` element to define the service
endpoint. The default value of the [hotspot=httpPort file=0]`default.http.port`
variable is `9081`. However, this value is only used if no other value is
specified. To find a value for this variable, Open Liberty looks for the
following environment variables, in order:

* `default.http.port`
* `default_http_port`
* `DEFAULT_HTTP_PORT`

When you previously ran the `inventory` container, none of the environment variables mentioned were defined and thus the default value of `9081` was used.

Run the following commands to stop and remove the `inventory` container and rerun it with the `default.http.port` environment variable set:

[role='command']
```
podman stop inventory
podman rm inventory 
podman run -d --name inventory -e default.http.port=9091 -p 9091:9091 inventory:1.0-SNAPSHOT
```

The `-e` flag can be used to create and set the values of environment variables
in a Podman container. In this case, you are setting the `default.http.port` environment
variable to `9091` for the `inventory` container.

Now, when the service is starting up, Open Liberty finds the
`default.http.port` environment variable and uses it to set the value of the
[hotspot=httpPort file=0]`default.http.port` variable to be used in the HTTP
endpoint.

// static guide instructions:
ifndef::cloud-hosted[]
The `inventory` service is now available on the new port number that you
specified. You can see the contents of the inventory at the 
http://localhost:9091/inventory/systems[http://localhost:9091/inventory/systems^] URL.
You can add your local system properties at
`\http://localhost:9091/inventory/systems/pass:c[[system-ip-address]]` by
replacing `[system-ip-address]` with the IP address that you obtained in the previous
section. The `system` service remains unchanged and is available at the
http://localhost:9080/system/properties[http://localhost:9080/system/properties^] URL.
endif::[]

// cloud-hosted guide instructions:
ifdef::cloud-hosted[]
The **inventory** service is now available on the new port number that you
specified. You can see the contents of the inventory at the
**http://localhost:9091/inventory/systems** URL. Run the following curl command:
```
curl -s http://localhost:9091/inventory/systems | jq
```
{: codeblock}

You can add your local system properties at the
**http://localhost:9091/inventory/systems/[system-ip-address]** URL by
replacing **[system-ip-address]** with the IP address that you obtained in the previous
section. Run the following commands:
```
SYSTEM_IP=`podman inspect -f "{{.NetworkSettings.IPAddress }}" system`
curl -s http://localhost:9091/inventory/systems/{$SYSTEM_IP} | jq
```
{: codeblock}

The **system** service remains unchanged and is available at the
**http://localhost:9080/system/properties** URL. Run the following curl command:
```
curl -s http://localhost:9080/system/properties | jq
```
{: codeblock}
endif::[]

You can externalize the configuration of more than just the port numbers.
To learn more about Open Liberty server configuration, check out the
https://openliberty.io/docs/latest/reference/config/server-configuration-overview.html[Server Configuration Overview^] docs. 

== Testing the microservices

You can test your microservices manually by hitting the endpoints or with automated tests that check your running Podman containers.

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `SystemEndpointIT` class.#
`system/src/test/java/it/io/openliberty/guides/system/SystemEndpointIT.java`
----

SystemEndpointIT.java
[source, java, linenums, indent=0, role="code_column hide_tags=copyright"]
----
include::finish/system/src/test/java/it/io/openliberty/guides/system/SystemEndpointIT.java[]
----

The [hotspot=testGetProperties file=0]`testGetProperties()` method checks for a `200` response code from the `system` service endpoint.

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `InventoryEndpointIT` class.#
`inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java`
----

InventoryEndpointIT.java
[source, java, linenums, indent=0, role="code_column hide_tags=copyright"]
----
include::finish/inventory/src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointIT.java[]
----

* The [hotspot=testEmptyInventory file=1]`testEmptyInventory()` method checks that the `inventory` service has a total of 0 systems before anything is added to it.
* The [hotspot=testHostRegistration file=1]`testHostRegistration()` method checks that the `system` service was added to `inventory` properly.
* The [hotspot=testSystemPropertiesMatch file=1]`testSystemPropertiesMatch()` checks that the `system` properties match what was added into the `inventory` service.
* The [hotspot=testUnknownHost file=1]`testUnknownHost()` method checks that an error is raised if an unknown host name is being added into the `inventory` service.
* The [hotspot=systemServiceIp file=1]`systemServiceIp` variable has the same value as what you retrieved in the previous section when manually adding the `system` service into the `inventory` service. This value of the IP address is passed in when you run the tests.

=== Running the tests
// static guide instructions
ifndef::cloud-hosted[]
Run the Maven `package` goal to compile the test classes. Run the Maven `failsafe` goal to test the services that are running in the Podman containers by replacing the `[system-ip-address]` with the IP address that you determined previously.

[role='command']
```
mvn package
mvn failsafe:integration-test -Dsystem.ip=[system-ip-address] -Dinventory.http.port=9091 -Dsystem.http.port=9080
```
endif::[]

// cloud-hosted guide instructions
ifdef::cloud-hosted[]
Run the Maven **package** goal to compile the test classes. Run the Maven **failsafe** goal to test the services that are running in the Podman containers by setting **-Dsystem.ip** to the IP address that you determined previously.

```
SYSTEM_IP=`podman inspect -f "{{.NetworkSettings.IPAddress }}" system`
mvn package
mvn failsafe:integration-test -Dsystem.ip="$SYSTEM_IP" -Dinventory.http.port=9091 -Dsystem.http.port=9080
```
{: codeblock}
endif::[]

If the tests pass, you see a similar output as the following:

[role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointIT
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.653 s - in it.io.openliberty.guides.system.SystemEndpointIT

Results:

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.inventory.InventoryEndpointIT
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.935 s - in it.io.openliberty.guides.inventory.InventoryEndpointIT

Results:

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
----

When you are finished with the services, run the following commands to stop and remove your containers:

[role='command']
```
podman stop inventory system 
podman rm inventory system
```


== Great work! You're done!

You have just built Podman images and run two microservices on Open Liberty in containers. 

include::{common-includes}/attribution.adoc[]
